volumes:
  pg_data:
  static:
  media:
  frontend_build:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: nazhia/foodgram_backend
    env_file: .env
    volumes:
      - ./data:/data:cached
      - static:/static
      - media:/media
    depends_on:
      - db
  frontend:
    container_name: foodgram-front
    image: nazhia/foodgram_frontend
    volumes:
      - frontend_build:/app/result_build
  nginx:
    container_name: foodgram-proxy
    image: nazhia/foodgram_nginx
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
      - media:/media
      - frontend_build:/usr/share/nginx/html
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend