# Generated by Django 3.2.16 on 2025-06-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20250606_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
