# Generated by Django 3.2.16 on 2025-06-11 18:14

from django.db import migrations
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Tag = apps.get_model('recipes', 'Tag')
    for tag in Tag.objects.filter(slug__isnull=True):
        tag.slug = slugify(tag.name, allow_unicode=False)
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20250608_1333'),
    ]

    operations = [
        migrations.RunPython(generate_slugs,
                             reverse_code=migrations.RunPython.noop),
    ]
