# Generated by Django 3.2.16 on 2025-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_follow_prevent_self_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='users/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
